### ISSUE TITLE
grouping device

### ISSUE THREAD

**Issue by asepkampak** [ytti/oxidized-web#89]
hai, i want to ask, how to make grouping device on oxidized for example based on location, all my device now belonging default group. please some advice.

**Comment by ytti** [comment]
Are you using CSV source, like router.db? Then you'll need something like this

```
source:
  csv:
    map:
      name: 0
      model: 1
      group: 2
```

And your router.db then should be like

```
router1:ios:london
router2:junos:sandiego
```
